// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iit.crossplateforme.Data;

namespace iit.crossplateforme.Data.Migrations
{
    [DbContext(typeof(PatientContext))]
    [Migration("20220115200237_patient")]
    partial class patient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("iit.crossplateforme.Domain.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthCare")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TelNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FamilyName = "chaker",
                            HealthCare = "Flu",
                            Name = "Amine",
                            TelNumber = 12345
                        },
                        new
                        {
                            Id = 2L,
                            FamilyName = "felah",
                            HealthCare = "Allergies",
                            Name = "Nawel",
                            TelNumber = 22335
                        },
                        new
                        {
                            Id = 3L,
                            FamilyName = "zouari",
                            HealthCare = "Headaches",
                            Name = "ahlem",
                            TelNumber = 22365
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
